import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/layout/Header";

const openSans = Open_Sans({
  subsets: ["latin", "latin-ext", "vietnamese"],
  weight: ["400", "700"], // 必要なウェイトを指定
  variable: "--font-open-sans", // カスタムCSSプロパティ
});

export const metadata: Metadata = {
  title: "Dmission",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={openSans.variable}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
